<?php

/**
 * Implements hook_modules_installed().
 */
function acsf_modules_installed($modules) {
  acsf_build_registry();
}

/**
 * Builds the registry of ACSF compatible class files.
 */
function acsf_build_registry() {
  // Create a registry of ACSF compatible classes.
  $registry = \Drupal::moduleHandler()->invokeAll('acsf_registry');

  usort($registry['events'], 'acsf_registry_sort');

  \Drupal::service('acsf.variable_storage')->set('acsf_registry', $registry);
}

/**
 * Determines sort order for usort.
 */
function acsf_registry_sort($a, $b) {
  if (!isset($a['weight'])) {
    $a['weight'] = 0;
  }
  if (!isset($b['weight'])) {
    $b['weight'] = 0;
  }
  if ($a['weight'] == $b['weight']) {
    return 0;
  }
  return ($a['weight'] < $b['weight']) ? -1 : 1;
}

/**
 * Retrieves the registry of class files.
 */
function acsf_get_registry() {
  return \Drupal::service('acsf.variable_storage')->get('acsf_registry', array());
}

/**
 * Implements hook_acsf_registry().
 */
function acsf_acsf_registry() {
  return array(
    'events' => array(
      array(
        'weight' => -1,
        'type' => 'acsf_install',
        'class' => '\Drupal\acsf\Event\AcsfSiteInfoHandler',
      ),
    ),
  );
}

/**
 * Implements hook_cron().
 */
function acsf_cron() {
  // Periodically refresh the site data.
  $site = \Drupal\acsf\AcsfSite::load();
  $refresh_age = time() - 86400;
  if ($site->last_sf_refresh < $refresh_age) {
    $site->refresh();
  }
}
